version: '3'
services:
  client:
    build: ./client
    ports:
      - "81:7777"
    environment:
      - REDIS_HOST=redis
      - SERVICE_HOST=back
      - SERVICE_PORT=3000
    depends_on:
      - back
      - redis
  redis:
    image: "redis:alpine"
  mongo:
    image: "mongo:latest"
  back:
    build: ./server
    ports:
      - "82:3000"
    environment:
      - DB_HOST=mongo
      - PORT=3000
  data:
    build: ./data-importer
    depends_on:
      - back
    links:
      - "back:back"
