version: '3'
services:
  client:
    image: "dkfn/coct-client:dev"
    ports:
      - "81:7777"
    environment:
      - REDIS_HOST=redis
  redis:
    image: "redis:alpine"
  mongo:
    image: "mongo:latest"
  back:
    image: "dkfn/coct-server:dev"
    ports:
      - "82:3000"
    environment:
      - PORT=3000