version: '3'
services:
  client:
    image: "dkfn/coct-client:dev"
    ports:
      - "81:7777"
    environment:
      - REDIS_HOST=redis
      - SERVICE_HOST=back
      - SERVICE_PORT=3000
    depends_on:
      - back
      - redis
  redis:
    image: "redis:alpine"
  mongo:
    image: "mongo:latest"
  back:
    image: "dkfn/coct-server:dev"
    ports:
      - "82:3000"
    environment:
      - DB_HOST=mongo
      - PORT=3000
    depends_on:
      - mongo
  data_importer:
    image: "dkfn/coct-dataimporter:dev"
    depends_on:
      - back
